name: Build QMK and ZMK Firmware

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-qmk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout QMK
      uses: actions/checkout@v4
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        
    - name: Checkout keymap
      uses: actions/checkout@v4
      with:
        path: keyboards/crkbd/keymaps/custom
        sparse-checkout: |
          qmk/
        
    - name: Copy keymap files
      run: |
        cp keyboards/crkbd/keymaps/custom/qmk/* keyboards/crkbd/keymaps/custom/
        rm -rf keyboards/crkbd/keymaps/custom/qmk
        
    - name: Install QMK CLI
      run: python3 -m pip install qmk
      
    - name: Setup QMK
      run: |
        qmk setup -H ${{ github.workspace }} -y
        qmk config user.keyboard=crkbd
        qmk config user.keymap=custom
        
    - name: Build firmware
      run: qmk compile -kb crkbd -km custom
      
    - name: Export keymap JSON
      run: qmk c2json -kb crkbd -km custom > keymap.json
      
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: qmk-firmware
        path: |
          *.hex
          *.json
        retention-days: 30

  build-zmk:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    
    steps:
    - name: Checkout ZMK
      uses: actions/checkout@v4
      with:
        repository: zmkfirmware/zmk
        ref: main
        
    - name: Checkout keymap
      uses: actions/checkout@v4
      with:
        path: app/boards/shields/corne/custom
        sparse-checkout: |
          zmk/
        
    - name: Copy keymap files
      run: |
        mkdir -p config
        cp -r app/boards/shields/corne/custom/zmk/config/* config/
        
    - name: Initialize west workspace
      run: |
        cd app
        west init -l .
        west update
        west zephyr-export
        
    - name: Build ZMK firmware (left)
      run: |
        cd app
        west build -d build/left -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="../config"
        
    - name: Build ZMK firmware (right)
      run: |
        cd app
        west build -d build/right -b nice_nano_v2 -- -DSHIELD=corne_right -DZMK_CONFIG="../config"
        
    - name: Copy firmware files
      run: |
        cp app/build/left/zephyr/zmk.uf2 corne_left-nice_nano_v2-zmk.uf2
        cp app/build/right/zephyr/zmk.uf2 corne_right-nice_nano_v2-zmk.uf2
        
    - name: Upload ZMK firmware
      uses: actions/upload-artifact@v4
      with:
        name: zmk-firmware
        path: |
          *.uf2
        retention-days: 30
